- name: set hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}


- name: Copy redis repo 
  ansible.builtin.copy:
    src: "{{COMPONENT}}.repo"
    dest: /etc/yum.repos.d/{{COMPONENT}}.repo


- name: Installing {{COMPONENT}}  
  ansible.builtin.package:
    name: "{{COMPONENT}}-6.2.11"
    state: present 

- name: Updating {{COMPONENT}} Config
  ansible.builtin.replace:
    path: /etc/{{COMPONENT}}/{{COMPONENT}}.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start {{COMPONENT}}
  ansible.builtin.service:
    name: "{{COMPONENT}}"
    state: started         
    enabled: yes