
    
- name: Copy file from Destination 
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Restarting Service 
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true 
    name: "{{COMPONENT}}"
    enabled: yes

