- name: Copying MySQL Repo 
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Installing MySQL 
  ansible.builtin.yum:
    name: 
      - mysql-community-server
      - MySQL-python
    state: installed   

- name: Restarting Service 
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes 

- name: Get MySQL version with non-default credentials
  mysql_info:
    login_user: root
    login_password: RoboShop@1
  ignore_errors: true
  register: stat 

- name: Reset Password
  when: stat.failed
  block:
      - name: fetch mysql default credentials
        ansible.builtin.shell: grep "temporary password" /var/log/mysqld.log | awk '{print $NF}'
        register: DEF_ROOT_PASSWORD
        
      - name: Copying MySQL Reset Password File
        ansible.builtin.copy:
          src: rootpass.sql
          dest: /tmp/rootpass.sql

      - name: Reset MySQL default password
        ansible.builtin.shell: mysql --connect-expired-password -uroot -p"{{DEF_ROOT_PASSWORD.stdout}}" < /tmp/rootpass.sql
        register: DEF_ROOT_PASSWORD

- name: Checking password validate Plugins 
  ansible.builtin.shell: echo show plugins; | mysql -uroot -pRoboShop@1 | grep validate_password
  register: PLUGIN_INFO
  ignore_errors: true

- name: Reset Password
  when: PLUGIN_INFO.rc == 0
  block:
      - name: Copying the command 
        ansible.builtin.copy:
          src: validatepass.cmd
          dest: /tmp/validatepass.cmd

      - name: Removing password validate Plugins 
        ansible.builtin.shell: mysql --connect-expired-password -uroot -pRoboShop@1 < /tmp/validatepass.cmd

- name: Download and extract
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: load schema 
  community.mysql.mysql_db:
    state: import
    name: all
    target: /tmp/mysql-main/shipping.sql
    login_user: root
    login_password: RoboShop@1