- name: demo in priveleg escalation
  hosts: all
  become: yes
  tasks: 
    - name: Running a shell commmand
      ansible.builtin.shell: id 
      register: out
    - name: Pritning Variable
      ansible.builtin.debug:
        msg: My id is "{{out.stdout}}"
    - name: Running a shell commmand
      ansible.builtin.shell: id 
      register: out
      become_user: centos
    - name: Pritning Variable
      ansible.builtin.debug:
        msg: My id is "{{out.stdout}}"
        