
- name: copy MongoDB repo to destination
  ansible.builtin.copy: 
    src: mongo.repo
    dest: /etc/yum.repos.d/{{COMPONENT}}.repo


- name: Installing {{COMPONENT}}-org  
  ansible.builtin.yum:
    name: "{{COMPONENT}}-org"
    state: installed 

- name: Updating {{COMPONENT}} Config
  ansible.builtin.replace:
    path: /etc/{{COMPONENT}}.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start {{COMPONENT}}
  ansible.builtin.service:
    name: mongod
    state: started         
    enabled: yes

- name: Download and extract
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: load {{COMPONENT}} schema
  community.mongodb.mongodb_shell:
    file: "/tmp/{{COMPONENT}}-main/{{item}}.js"
    idempotent: yes
  loop:
    - catalogue
    - users

    
- name: Set hostname
  ansible.builtin.include_role:
    name: common 
    tasks_from: sethostname
