- name: Installing MAVEN 
  ansible.builtin.package:
    name: maven 
    state: present




- name: create roboshop user account
  ansible.builtin.include_role:
    name: common
    tasks_from: create-user


- name: Download and extract
  ansible.builtin.include_role:
    name: common
    tasks_from: download


- name: Cleanup old content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent


- name: copy file to destination 
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
  become_user: roboshop

- name: Creating the package
  ansible.builtin.shell: mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar 
  args:
    chdir: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: Configure services
  ansible.builtin.include_role:
    name: common
    tasks_from: configuringservice